### ISSUE TITLE
Can only hold one Money at a time

### ISSUE THREAD

**Issue by thomsedavi** [The-Team-Awesome/Zompocalypse#8]
Attempting to pick up more than one Money will result in subsequent Moneys being deleted

**Comment by Sam-Costigan** [comment]
It does actually add them to the players currently held Money, but the image stays at whatever the first money picked up was. It might be more helpful to change this to the highest value and maybe draw the Money's count as well?

**Comment by thomsedavi** [comment]
OIC that makes sense. I picked up some Bronze and then some Gold and saw only Bronze coins, so this would need to be separated at least. But showing the accumulated Amount of each Money would be useful.

**Comment by Sam-Costigan** [comment]
I've made different stacks for each type of money and given a count to the money as well.
